AzureEventSite/Controllers/AdminController.cs
using AzureEventSite.Helpers;
using AzureEventSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.WindowsAzure.Storage;

namespace AzureEventSite.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                using (var context = new AzureTentanEntities())
                {
                    string currentUserName = User.Identity.Name;
                    var currentuser = context.Users.FirstOrDefault(u => u.UserName == currentUserName);

                    if (currentuser.IsAdmin)
                    {
                        List<EventDisplayModel> model = new List<EventDisplayModel>();

                        var allEvents = context.Events.ToList();   

                        foreach (var item in allEvents)
                        {
                            var publisher = context.Users.FirstOrDefault(u => u.ID == item.PublisherID);

                            var eventToAdd = new EventDisplayModel                            
                            { 
                                Id = item.ID,
                                Name = item.Name,
                                Attenders = item.Attenders,
                                NonAttenders = item.NonAttenders,
                                Likes = item.Likes,
                                Dislikes = item.Dislikes,
                                Date = item.Date,
                                Creater = publisher.UserName,                      
                            };

                            model.Add(eventToAdd);
                        }
                        
                        return PartialView("_Admin", model);
                    }
                }
            }
            return RedirectToAction("Index", "Home");
        }


        public ActionResult ShowComments()
        {
            List<CommentsDisplayModel> model = new List<CommentsDisplayModel>();

            using (var context = new AzureTentanEntities())
            {
               

                var allComments = context.Comments.ToList();

                foreach (var item in allComments)
                {
                    var commentToAdd = new CommentsDisplayModel 
                    {
                     CommentId = item.ID,
                     Comment = item.Content,
                     EventId = item.EventId,
                     CommentOwner = item.Username
                    };
                    model.Add(commentToAdd);
                }
            }
            return PartialView("_ShowComments", model);
        }

        public ActionResult ShowTable()
        {
            var account = CloudStorageAccount.Parse("DefaultEndpointsProtocol=https;AccountName=mittstoragetest;AccountKey=kxg+pXxFk0nVmYdM/BiUKtOXlLhR6jOgzqiPpj/QLImAY06M5bbAu/KR8tzLy8xZpg6548DNLjBzxqkYdWLZww==");

             var tableStorage = account.GetLogs(User.Identity.Name);
             List<LogModel> listOfTableStorage = new List<LogModel>();

             foreach (var item in tableStorage)
             {
                 var logToAdd = new LogModel 
                 {
                    EventName = item.EventName,
                    TimeOfEvent = item.TimeOfEvent,
                    Timestamp = item.Timestamp,
                    UserName = item.UserName,
                 };

                 listOfTableStorage.Add(logToAdd);
             }

             return PartialView("_ShowTable", listOfTableStorage);
        }
	}
}

AzureEventSite/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AzureEventSite.Models;
using System.Web.Security;
using AzureEventSite.UserHandlerServiceReference1;

namespace AzureEventSite.Controllers
{
    public class UserController : Controller
    {
        private UserService1Client proxy;

        public UserController()
        {
            proxy = new UserService1Client();
        }
        
        public ActionResult Index()
        {        

            return View();
        }

        [HttpGet]
        public ActionResult LogIn()
        {
            return PartialView("_LogIn");
        }

        [HttpPost]
        public ActionResult LogIn(UserModel user)
        {
            if (ModelState.IsValid)
            {
                if (proxy.IsLogInValid(user.UserName, user.PassWord))
                {

                    FormsAuthentication.SetAuthCookie(user.UserName, false);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Fel användarnamn eller lösenord");
                }             
            }

            return View(user);
        }

        [HttpGet]
        public ActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registration(UserModel user)
        {
            if (ModelState.IsValid)
            {
                var newUser = new RegisterModel { FirstName = user.FirstName, LastName = user.LastName, UserName = user.UserName, PassWord = user.PassWord };
                if (proxy.IsRegistrationValid(newUser))
                {
                    return RedirectToAction("Index", "Home");
                }             
            }

            return View(user);
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

	}
}

AzureEventSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>FOMO</title>
    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.css" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="~/css/business-casual.css" rel="stylesheet">

</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("HEM", "Index", "Home")
                    </li>
                    <li>
                        @Ajax.ActionLink("SKAPA ETT EVENT", "CreateEvent", "Home", new AjaxOptions { UpdateTargetId = "siteContent" })
                    </li>
                   @if (User.Identity.Name == "monkeyd")
                   {
                       <li>
                        @Ajax.ActionLink("ADMIN", "Index", "Admin", new AjaxOptions { UpdateTargetId = "siteContent" })
                    </li>
                   }                       
                    <li>
                       @Html.ActionLink("KONTAKTA ADMIN", "Contact", "Home")
                    </li>
                </ul>
                @if (Request.IsAuthenticated)
                {
                    <strong>@Html.Encode(User.Identity.Name)</strong>
                    @Html.ActionLink("Logga ut", "LogOut", "User")
                }
                else
                {
                    @Html.ActionLink("Skapa konto", "Registration", "User")
                    <span> | </span>
                    @Ajax.ActionLink("Logga in", "LogIn", "User", new AjaxOptions { UpdateTargetId = "siteContent" })
                }
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

   
    <div id="siteContent" class="container body-content">
        @RenderBody()

        <hr />
        <footer>
            <div style="background-color: darkgray; opacity:0.8;" class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <p>&copy; @DateTime.Now.Year - FOMO!</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <!-- JavaScript -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
</body>
</html>